### ISSUE TITLE
Connection state is not Open until there pause in R session

### ISSUE THREAD

**Issue by ef2240** [rstudio/websocket#27]
This is an odd issue I've run across in a couple of different platforms (details below). As best as I can tell, it was introduced by #16.

When I run the following command: 
`ws <- WebSocket$new("ws://echo.websocket.org/"); ws$readyState()`,
the response is `0L: Connecting`.

However, when running the the two commands separately, the response is `1L: Open`.

It is even such that inside Rstudio, when running `ws <- WebSocket$new("ws://echo.websocket.org/")` and then `ws$readyState()`, the response will be different depending on whether the two lines are both selected and run, or if they are run one at a time.

This issue manifests itself when sourcing a script. If the script were to contain:
```
ws <- WebSocket$new("ws://echo.websocket.org/")
ws$send("hello")
```
this would fail with the error message `Error in wsSend(private$wsObj, msg) : invalid state`. However, when run interactively, by running one line at a time, it would run without errors.

Finally, I'll note that I don't believe this is to be a timing issue per se. Instructing R to wait prior to checking the state (i.e. `ws <- WebSocket$new("ws://echo.websocket.org/"); Sys.sleep(5); ws$readyState()`) will still return `0L: Connecting`. On the other hand, when `ws <- WebSocket$new("ws://echo.websocket.org/")` is run on its own, running `ws$readyState()` immediately after will return `1L: Open`.

Session info:
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] websocket_0.0.0.9001

loaded via a namespace (and not attached):
[1] compiler_3.5.0 R6_2.2.2       later_0.7.4    tools_3.5.0    yaml_2.2.0     Rcpp_0.12.18   rlang_0.2.2  
```

It additionally fails under:
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] websocket_0.0.0.9001

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.5.0  R6_2.2.2        later_0.7.3    
 [5] tools_3.5.0     withr_2.1.2     curl_3.2        Rcpp_0.12.17   
 [9] memoise_1.1.0   git2r_0.21.0    jsonlite_1.5    digest_0.6.15  
[13] rlang_0.2.1     devtools_1.13.5
```

**Comment by MilesMcBain** [comment]
An excellent write up @ef2240.

Also seen on:
```

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] websocket_0.0.0.9001

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.5.1  R6_2.2.2        later_0.7.4    
 [5] tools_3.5.1     withr_2.1.2     curl_3.2        Rcpp_0.12.18   
 [9] memoise_1.1.0   git2r_0.23.0    digest_0.6.16   rlang_0.2.2    
[13] devtools_1.13.6

```

**Comment by alandipert** [comment]
Thanks for the report @ef2240. While this behavior doesn't constitute a bug, it's definitely a subtlety of WebSockets that we should probably at least address in the documentation.

It's surprising to many (it was to me!) that WebSockets behave differently depending on whether methods are evaluated simultaneously (as part of a code chunk or together inside a function body) or method-by-method (as in the console). The reason they behave differently is because of the single-threaded nature of R and the way [later](https://github.com/r-lib/later) works.

`later` is used internally by `websocket` to process events generated by the underlying websocketpp library. `later` initiates processing of the event queue when R isn't busy (the execution stack is empty).

The `new` method is not *synchronous*; that is, there's no guarantee after it returns that the WebSocket has connected. What `new` does is initiate the work of connecting and return immediately. That work is enqueued on `later`'s queue, which will be processed the moment R isn't busy.

When you ran `new` and `readyState` together as part of the same expression, something like this happened:

1. `new` (synchronously) set an internal state field to `Connecting` and then enqueued some number of functions on `later`'s queue to do the work of initiating the connection
1. `readyState` inspected the internal state field, which hasn't yet been manipulated by the functions that `new` enqueued, and it's still `Connecting`
1. (R stops being busy)
1. `later` processes enqueued functions, the connection is live, and subsequent calls to `readyState` report `Open`

When you ran `new` and `readyState` separately, something like this happened:

1. `new` set the state field to `Connecting` and enqueued the work
1. (R stops being busy)
1. `later` processing of the work enqueued by `new` happens
1. (later stops being busy)
1. `readyState` returns `Open` because the work of connecting has been completed

Because `new` is effectively asynchronous, it's also expected that calling `send` immediately after `new` won't necessarily work. The way around that is by setting the `onOpen` handler in your script and performing the `send` there, where the WebSocket is guaranteed to be connected:

```R
library(websocket)
ws <- WebSocket$new("ws://echo.websocket.org/")
ws$onMessage(function (e) cat(e$data, "\n"))
ws$onOpen(function (e) {
  ws$send("hello")
})
```

**Comment by ef2240** [comment]
@alandipert Thanks for the thorough explanation, it's really helpful. All good to go on my end.
