### ISSUE TITLE
The websocket shuts close without any events emitting

### ISSUE THREAD

**Issue by TheOnlyArtz** [rstudio/websocket#52]
I'm using the example code:
```r
library(websocket)

ws <- WebSocket$new("ws://echo.websocket.org/", autoConnect = FALSE)
ws$onOpen(function(event) {
  cat("Connection opened\n")
})
ws$onMessage(function(event) {
  cat("Client got msg: ", event$data, "\n")
})
ws$onClose(function(event) {
  cat("Client disconnected with code ", event$code,
    " and reason ", event$reason, "\n", sep = "")
})
ws$onError(function(event) {
  cat("Client failed to connect: ", event$message, "\n")
})
ws$connect()
```
and it just doesn't work, the process exists right away without anything getting printed to the console

**Comment by TheOnlyArtz** [comment]
Update, this code runs perfectly **from console** but it doesn't work from a file using `rscript filename.R`, any reason why?

**Comment by alandipert** [comment]
Hi, thanks for the report. Our documentation could definitely use some improvement, because [something extra](https://github.com/rstudio/websocket/issues/25#issuecomment-420455428) is necessary at the end for the example to work in a standalone R script:

```
while (TRUE) {
  later::run_now(1L)
}
```
In a nutshell, `ws$connect()` is asynchronous &mdash; it only schedules work via `later` &mdash; and so the R process has no problem exiting before any work has been done. `later::run_now()` in a loop continuously "pumps" work through later, blocking the R process and allowing the scheduled work to complete.

**Comment by alandipert** [comment]
I made #53 to track improving the docs, so please don't hesitate to close this issue if it solves your problem. Otherwise, I'm happy to discuss further.

**Comment by TheOnlyArtz** [comment]
Thank you btw!
